<? /*******************************************************************************
*   SubEther, The Decentralized Network.                                       *
*   Copyright (C) 2012 Friend Studios AS                                       *
*                                                                              *
*   This program is free software: you can redistribute it and/or modify       *
*   it under the terms of the GNU Affero General Public License as             *
*   published by the Free Software Foundation, either version 3 of the         *
*   License, or (at your option) any later version.                            *
*                                                                              *
*   This program is distributed in the hope that it will be useful,            *
*   but WITHOUT ANY WARRANTY; without even the implied warranty of             *
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
*   GNU Affero General Public License for more details.                        *
*                                                                              *
*   You should have received a copy of the GNU Affero General Public License   *
*   along with this program.  If not, see <https://www.gnu.org/licenses/>.     *
*******************************************************************************/ ?><?if ( $this->Content != '' ) { ?><div id="Admin">	<div class="Box">		<div class="tabs">			<table>				<tr>					<!--<td>						<a <?= ( $_REQUEST[ 'r' ] == 'case' ? 'class="current"' : '' ) ?> href="<?= $this->parent->route ?>?r=case">							<span></span>							<span>CaseList</span>						</a>					</td>-->					<!--<td>						<a <?= ( $_REQUEST[ 'r' ] == 'budget' ? 'class="current"' : '' ) ?> href="<?= $this->parent->route ?>?r=budget">							<span></span>							<span>Budget</span>						</a>					</td>-->					<!--<td>						<a <?= ( $_REQUEST[ 'r' ] == 'shopdb' ? 'class="current"' : '' ) ?> href="<?= $this->parent->route ?>?r=shopdb">							<span></span>							<span>ShopDB</span>						</a>					</td>-->					<!--<td>						<a <?= ( $_REQUEST[ 'r' ] == 'recruitment' ? 'class="current"' : '' ) ?> href="<?= $this->parent->route ?>?r=recruitment">							<span></span>							<span>Recruitment</span>						</a>					</td>-->					<td>						<a <?= ( $_REQUEST[ 'r' ] == 'orders' || $_REQUEST[ 'r' ] == '' ? 'class="current"' : '' ) ?> href="<?= $this->parent->route ?>?r=orders">							<span></span>							<span><?= i18n( 'i18n_Orders' ) ?></span>						</a>					</td>					<td>						<a <?= ( $_REQUEST[ 'r' ] == 'members' ? 'class="current"' : '' ) ?> href="<?= $this->parent->route ?>?r=members">							<span></span>							<span><?= i18n( 'i18n_Members' ) ?></span>						</a>					</td>					<td>						<a <?= ( $_REQUEST[ 'r' ] == 'accounting' ? 'class="current"' : '' ) ?> href="<?= $this->parent->route ?>?r=accounting">							<span></span>							<span><?= i18n( 'i18n_Accounting' ) ?></span>						</a>					</td>					<td>						<a <?= ( $_REQUEST[ 'r' ] == 'import' ? 'class="current"' : '' ) ?> href="<?= $this->parent->route ?>?r=import">							<span></span>							<span><?= i18n( 'i18n_Import' ) ?></span>						</a>					</td>					<td>						<a <?= ( $_REQUEST[ 'r' ] == 'clients' ? 'class="current"' : '' ) ?> href="<?= $this->parent->route ?>?r=clients">							<span></span>							<span><?= i18n( 'i18n_Clients' ) ?></span>						</a>					</td>					<td>						<a <?= ( $_REQUEST[ 'r' ] == 'mailing' ? 'class="current"' : '' ) ?> href="<?= $this->parent->route ?>?r=mailing">							<span></span>							<span><?= i18n( 'i18n_Mailing' ) ?></span>						</a>					</td>				</tr>			</table>		</div>		<div id="AdminDate" class="datenavigate"><?= $this->Navigation ?></div>		<div id="AdminContent"><?= $this->Content ?></div>	</div></div><?}?>